services:
  db:
    image: postgres:16
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    entrypoint: ["./bin/dev-entrypoint"]
    command: ["./bin/dev"]
    tty: true
    stdin_open: true
    volumes:
      - .:/scenapla
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/scenapla/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  bundle_data:
  postgresql_data:
  node_modules:
